### ISSUE TITLE
Inconsistent behaviour of `state.get()`

### ISSUE THREAD

**Issue by sbrodehl** [da-h/miniflask#71]
Using `state.get()` to retrieve state variables shows inconsistent behaviour, or often does not work at all.

**Comment by da-h** [comment]
Hi,

#90 ensures that `state` is indeed usable as a full-fledged dict. Thus, **this bug should be fixed in the upcoming miniflask release `v2.3`**.

If this issue still persists, please feel free to open a new issue / reopen this issue and **provide a minimal example showing the unexpected behavior**.

Best,
*da-h*

**Comment by sbrodehl** [comment]
Thank you very much, will test asap!
